package View;

public final class HtmlView {

    private HtmlView() {
    }

    public static String css() {
        return ":root {\n"
            + "    --bg: #eef4ff;\n"
            + "    --bg-soft: #f8fbff;\n"
            + "    --panel: rgba(255, 255, 255, 0.9);\n"
            + "    --panel-strong: #ffffff;\n"
            + "    --ink: #14213d;\n"
            + "    --muted: #52607a;\n"
            + "    --accent: #2563eb;\n"
            + "    --accent-dark: #1d4ed8;\n"
            + "    --accent-soft: #dbeafe;\n"
            + "    --border: #c8d7f2;\n"
            + "    --shadow: 0 20px 45px rgba(37, 99, 235, 0.12);\n"
            + "}\n"
            + "* { box-sizing: border-box; }\n"
            + "body {\n"
            + "    margin: 0;\n"
            + "    font-family: Georgia, \"Times New Roman\", serif;\n"
            + "    background:\n"
            + "        radial-gradient(circle at top right, rgba(37, 99, 235, 0.14), transparent 24%),\n"
            + "        radial-gradient(circle at left center, rgba(14, 165, 233, 0.16), transparent 28%),\n"
            + "        linear-gradient(180deg, #f8fbff 0%, var(--bg) 100%);\n"
            + "    color: var(--ink);\n"
            + "}\n"
            + ".shell {\n"
            + "    max-width: 1180px;\n"
            + "    margin: 0 auto;\n"
            + "    padding: 24px 18px 36px;\n"
            + "}\n"
            + "h1, h2, h3, p { margin-top: 0; }\n"
            + ".hero {\n"
            + "    padding: 28px;\n"
            + "    border: 1px solid var(--border);\n"
            + "    border-radius: 28px;\n"
            + "    background:\n"
            + "        linear-gradient(135deg, rgba(37, 99, 235, 0.1), rgba(248, 251, 255, 0.94)),\n"
            + "        var(--panel-strong);\n"
            + "    box-shadow: var(--shadow);\n"
            + "    margin-bottom: 18px;\n"
            + "}\n"
            + ".eyebrow {\n"
            + "    display: inline-block;\n"
            + "    padding: 6px 10px;\n"
            + "    border-radius: 999px;\n"
            + "    background: var(--accent-soft);\n"
            + "    color: var(--accent-dark);\n"
            + "    font-size: 12px;\n"
            + "    letter-spacing: 0.08em;\n"
            + "    text-transform: uppercase;\n"
            + "    margin-bottom: 12px;\n"
            + "}\n"
            + ".hero h1 {\n"
            + "    font-size: clamp(32px, 5vw, 52px);\n"
            + "    line-height: 0.95;\n"
            + "    margin-bottom: 12px;\n"
            + "}\n"
            + ".hero p {\n"
            + "    max-width: 720px;\n"
            + "    color: var(--muted);\n"
            + "    font-size: 17px;\n"
            + "    line-height: 1.6;\n"
            + "}\n"
            + "nav {\n"
            + "    display: flex;\n"
            + "    gap: 10px;\n"
            + "    flex-wrap: wrap;\n"
            + "    margin: 0 0 18px;\n"
            + "}\n"
            + "nav a {\n"
            + "    text-decoration: none;\n"
            + "    padding: 10px 14px;\n"
            + "    border-radius: 999px;\n"
            + "    background: rgba(255, 255, 255, 0.86);\n"
            + "    border: 1px solid var(--border);\n"
            + "    color: var(--ink);\n"
            + "    box-shadow: 0 8px 20px rgba(37, 99, 235, 0.08);\n"
            + "}\n"
            + "nav a:hover { background: var(--accent-soft); }\n"
            + ".grid {\n"
            + "    display: grid;\n"
            + "    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n"
            + "    gap: 16px;\n"
            + "}\n"
            + ".card {\n"
            + "    background: var(--panel);\n"
            + "    border: 1px solid var(--border);\n"
            + "    border-radius: 22px;\n"
            + "    padding: 18px;\n"
            + "    box-shadow: var(--shadow);\n"
            + "    backdrop-filter: blur(10px);\n"
            + "}\n"
            + ".card h2 {\n"
            + "    margin-bottom: 8px;\n"
            + "    font-size: 24px;\n"
            + "}\n"
            + ".lede {\n"
            + "    color: var(--muted);\n"
            + "    margin-bottom: 14px;\n"
            + "    line-height: 1.55;\n"
            + "}\n"
            + ".stats {\n"
            + "    display: grid;\n"
            + "    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));\n"
            + "    gap: 12px;\n"
            + "    margin-top: 18px;\n"
            + "}\n"
            + ".stat {\n"
            + "    padding: 14px;\n"
            + "    border-radius: 18px;\n"
            + "    border: 1px solid var(--border);\n"
            + "    background: rgba(255, 255, 255, 0.62);\n"
            + "}\n"
            + ".stat strong {\n"
            + "    display: block;\n"
            + "    font-size: 28px;\n"
            + "    margin-bottom: 4px;\n"
            + "    color: var(--accent-dark);\n"
            + "}\n"
            + ".section-title {\n"
            + "    margin: 24px 0 12px;\n"
            + "    font-size: 26px;\n"
            + "}\n"
            + "label {\n"
            + "    display: block;\n"
            + "    margin: 10px 0 5px;\n"
            + "    font-weight: bold;\n"
            + "    color: var(--accent-dark);\n"
            + "}\n"
            + "input {\n"
            + "    width: 100%;\n"
            + "    border: 1px solid var(--border);\n"
            + "    border-radius: 12px;\n"
            + "    padding: 10px 12px;\n"
            + "    background: rgba(255, 255, 255, 0.9);\n"
            + "    color: var(--ink);\n"
            + "}\n"
            + "input::placeholder { color: #9c8374; }\n"
            + "button {\n"
            + "    margin-top: 12px;\n"
            + "    border: 0;\n"
            + "    border-radius: 999px;\n"
            + "    background: var(--accent);\n"
            + "    color: white;\n"
            + "    padding: 10px 15px;\n"
            + "    cursor: pointer;\n"
            + "    font-weight: bold;\n"
            + "    letter-spacing: 0.02em;\n"
            + "}\n"
            + "button:hover { background: var(--accent-dark); }\n"
            + "form + form {\n"
            + "    margin-top: 14px;\n"
            + "    padding-top: 14px;\n"
            + "    border-top: 1px solid var(--border);\n"
            + "}\n"
            + "table {\n"
            + "    width: 100%;\n"
            + "    border-collapse: collapse;\n"
            + "    margin-top: 12px;\n"
            + "    font-size: 14px;\n"
            + "}\n"
            + "th {\n"
            + "    color: var(--accent-dark);\n"
            + "    font-size: 12px;\n"
            + "    letter-spacing: 0.08em;\n"
            + "    text-transform: uppercase;\n"
            + "}\n"
            + "th, td {\n"
            + "    border-bottom: 1px solid var(--border);\n"
            + "    text-align: left;\n"
            + "    padding: 10px 8px;\n"
            + "}\n"
            + ".msg {\n"
            + "    border: 1px solid #edc98f;\n"
            + "    background: #fff2dd;\n"
            + "    border-radius: 16px;\n"
            + "    padding: 12px 14px;\n"
            + "    margin-bottom: 14px;\n"
            + "    box-shadow: 0 10px 25px rgba(37, 99, 235, 0.08);\n"
            + "}\n"
            + ".footer-note {\n"
            + "    margin-top: 20px;\n"
            + "    color: var(--muted);\n"
            + "    font-size: 14px;\n"
            + "    text-align: center;\n"
            + "}\n"
            + "@media (max-width: 700px) {\n"
            + "    .hero { padding: 22px; }\n"
            + "    .card { padding: 16px; }\n"
            + "    nav a { flex: 1 1 calc(50% - 10px); text-align: center; }\n"
            + "}\n";
    }

    public static String page(String title, String content) {
        return "<!doctype html>\n"
            + "<html lang='pt-BR'>\n"
            + "<head>\n"
            + "  <meta charset='utf-8'>\n"
            + "  <meta name='viewport' content='width=device-width,initial-scale=1'>\n"
            + "  <title>" + title + "</title>\n"
            + "  <link rel='stylesheet' href='/styles.css'>\n"
            + "</head>\n"
            + "<body>\n"
            + "  <div class='shell'>\n"
            + content
            + "  </div>\n"
            + "</body>\n"
            + "</html>\n";
    }

    public static String nav() {
        return "<nav>\n"
            + "  <a href='/'>Loja Online</a>\n"
            + "  <a href='/clientes'>Clientes</a>\n"
            + "  <a href='/produtos'>Catalogo</a>\n"
            + "  <a href='/cupons'>Cupons</a>\n"
            + "  <a href='/pedidos'>Pedidos</a>\n"
            + "</nav>\n";
    }

    public static String msgBox(String msg, String escaped) {
        if (msg == null || msg.trim().isEmpty()) {
            return "";
        }
        return "<div class='msg'>" + escaped + "</div>";
    }
}
